### ISSUE TITLE
Feature: pose/fps (data type: int64) is required but could not be found.

### ISSUE THREAD

**Issue by a-rios** [sign-language-processing/datasets#23]
Hey Amit, 
I ran into an issue when trying to load the predefined splits for dgs. Minimal example: 

```
config = DgsCorpusConfig(name="3.0.0-uzh-sentence", version="3.0.0", include_video=False, data_type="sentence" ,include_pose="holistic", split="3.0.0-uzh-sentence", fps=50)
dgs= tfds.load(name=name, builder_kwargs=dict(config=config), data_dir=data_dir)

for split in dgs:
     for s in dgs[split]:
           ...
```
The iteration fails with: 
```
WARNING:absl:Using custom data configuration 3.0.0-uzh-sentence
2022-10-05 16:54:56.006077: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-05 16:54:57.199404: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1612] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 30969 MB memory:  -> device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:16:00.0, compute capability: 7.0
2022-10-05 16:54:58.472491: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at example_parsing_ops.cc:94 : INVALID_ARGUMENT: Feature: pose/fps (data type: int64) is required but could not be found.
2022-10-05 16:54:58.472648: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at example_parsing_ops.cc:94 : INVALID_ARGUMENT: Feature: pose/fps (data type: int64) is required but could not be found.
2022-10-05 16:54:58.472875: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at example_parsing_ops.cc:94 : INVALID_ARGUMENT: Feature: pose/fps (data type: int64) is required but could not be found.
Traceback (most recent call last):
  File "/home/cluster/arios/data/software/conda_stuff/envs/sockeye-continuous/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2022-10-05 16:54:58.474005: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at example_parsing_ops.cc:94 : INVALID_ARGUMENT: Feature: pose/fps (data type: int64) is required but could not be found.
    return _run_code(code, main_globals, None,
  File "/home/cluster/arios/data/software/conda_stuff/envs/sockeye-continuous/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/net/cephfs/data/arios/software/sockeye-continuous-output-3.1/sockeye/get_dgs.py", line 349, in <module>
    text_samples, gloss_samples, pose_samples, pose_header, normalization_info, fps = get_split_data(data_dir=args.tf_data_dir, components=args.components, joints=joints, full_holistic=args.full_holistic)
  File "/net/cephfs/data/arios/software/sockeye-continuous-output-3.1/sockeye/get_dgs.py", line 111, in get_split_data
    for s in dgs[split]:
  File "/home/cluster/arios/data/software/conda_stuff/envs/sockeye-continuous/lib/python3.9/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 787, in __next__
    return self._next_internal()
  File "/home/cluster/arios/data/software/conda_stuff/envs/sockeye-continuous/lib/python3.9/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 770, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/home/cluster/arios/data/software/conda_stuff/envs/sockeye-continuous/lib/python3.9/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3017, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/home/cluster/arios/data/software/conda_stuff/envs/sockeye-continuous/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 7215, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_25_device_/job:localhost/replica:0/task:0/device:CPU:0}} Feature: pose/fps (data type: int64) is required but could not be found.
         [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]] [Op:IteratorGetNext]
```
Please help :)

**Comment by a-rios** [comment]
ok, my bad, I was using a cached version of the corpus that did not have poses. After deleting + downloading fresh, it works as expected :)
